# Generated by Django 3.0.3 on 2020-09-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ('name',), 'verbose_name': 'year', 'verbose_name_plural': 'year'},
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='year',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
