# Generated by Django 3.0.3 on 2020-09-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200913_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('files', models.FileField(null=True, upload_to='')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='notes.Year')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ('name',),
            },
        ),
    ]
