# Generated by Django 3.0.3 on 2021-02-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=2)),
                ('subject', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('files', models.FileField(null=True, upload_to='pdfs')),
            ],
            options={
                'ordering': ('year',),
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year',
        ),
        migrations.RemoveField(
            model_name='year',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
